[tool.poetry]
name = "trying-k-means"
version = "1.0.0"
description = "ğŸ¥—ğŸ¥—ğŸ¥— Pythonã§K-meansã‚’å®Ÿè£…ã—ã¦ã¿ã‚‹ï¼"
authors = ["osawa-koki <koki@osawa.dev>"]
license = "Apache-2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
numpy = "^2.0.1"
matplotlib = "^3.9.1"
scikit-learn = "^1.5.1"

[tool.poetry.group.dev.dependencies]
flake8 = "^7.0.0"
black = "^23.11.0"
isort = "^5.12.0"
mypy = "^1.7.0"
pytest = "^7.4.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
